User_Dashboard_Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.LoginAndReg.urls', namespace = "login")),
    url(r'^UserDashboard/', include('apps.UserDashboard.urls', namespace = "UserDashboard"))
]

apps/LoginAndReg/urls.py
from django.conf.urls import url, include # Notice we added include
from . import views

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^users$', views.register, name = "register"),
	url(r'^login$', views.login, name = "login"),
	url(r'^updateInfo/(?P<id>\d+)$', views.updateInfo, name = "updateInfo"),
	url(r'^updatePassword/(?P<id>\d+)$', views.updatePassword, name = "updatePassword"),
	url(r'^updateDescription$', views.updateDescription, name = "updateDescription"),
	url(r'^removeUser/(?P<id>\d+)$', views.removeUser, name = "removeUser"),
	url(r'^createUser$', views.createUser, name = "createUser")
	]

apps/UserDashboard/urls.py
from django.conf.urls import url, include # Notice we added include
from . import views

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^users/new$', views.createDisplay, name = "createDisplay"),
	url(r'^users/edit$', views.editProfileDisplay, name = "editProfileDisplay"),
	url(r'^showWall/(?P<id>\d+)$', views.showWall, name = "showWall"),
	url(r'^postMessage$', views.postMessage, name = "postMessage"),
	url(r'^deleteMessage/(?P<id>\d+)$', views.deleteMessage, name = "deleteMessage"),
	url(r'^postComment/(?P<id>\d+)$', views.postComment, name = "postComment"),
	url(r'^deleteComment/(?P<id>\d+)$', views.deleteComment, name = "deleteComment"),
	url(r'^logout$', views.logout, name = "logout"),
	url(r'^users/edit/(?P<id>\d+)$', views.adminEdit, name = "adminEdit")
]

apps/UserDashboard/models.py
from __future__ import unicode_literals
from django.db import models
from ..LoginAndReg.models import User, LoginManager, RegisterManager
# Create your models here.

class Messages(models.Model):
	message = models.TextField()
	user = models.ForeignKey(User, related_name = "poster")
	reciever = models.ForeignKey(User, related_name = "reciever", null = True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Comments(models.Model):
	comment = models.TextField()
	message = models.ForeignKey(Messages)
	user = models.ForeignKey(User)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

apps/UserDashboard/views.py
from django.shortcuts import render, HttpResponse, redirect
from models import Messages, Comments
from ..LoginAndReg.models import User, LoginManager, RegisterManager
from django.core.urlresolvers import reverse
from django.db.models import Count 

def index(request):
	context = {
	    'users' : User.registerMgr.all(),
	    'activeUser': User.registerMgr.get(id = request.session['login'])
	}
	return render(request, 'UserDashboard/index.html', context)

def createDisplay(request):
	return render(request, 'UserDashBoard/newUser.html')

def editProfileDisplay(request):
	user = User.registerMgr.get(id = request.session['login'])
	context = {
		'User': user
	}
	return render(request, 'UserDashboard/editProfile.html',  context )

def adminEdit(request, id):
	user = User.registerMgr.get(id = id)
	context = {
		'User': user
	}
	return render(request, 'UserDashboard/adminEdit.html', context )


def showWall(request, id):
	messages = Messages.objects.filter(reciever_id = id).order_by('id')
	request.session['reciever'] = id
	comments = Comments.objects.all()
	context = {
		'all_messages': messages,
		'all_comments': comments,
		'user': User.registerMgr.get(id = id)
	}
	return render(request, 'UserDashboard/showWall.html',  context )

def postMessage(request):
	newMessage = Messages.objects.create(message = request.POST['message'], user_id = request.session['login'], reciever_id = request.session['reciever'] )
	url = "/UserDashboard/showWall/" + str(request.session['reciever'])
	return redirect(url)

def deleteMessage(request, id):
	Messages.objects.get(id = id).delete()
	url = "/UserDashboard/showWall/" + str(request.session['reciever'])
	return redirect(url)

def postComment(request, id):
	newComment = Comments.objects.create(comment = request.POST['comment'], user_id = request.session['login'], message_id = id)
	url = "/UserDashboard/showWall/" + str(request.session['reciever'])
	return redirect(url)

def deleteComment(request, id):
	Comments.objects.get(id = id).delete()
	url = "/UserDashboard/showWall/" + str(request.session['reciever'])
	return redirect(url)

def logout(request):
	request.session['login'] = 0
	request.session['reciever'] = 0
	return redirect(reverse('login:index'))

apps/UserDashboard/templates/UserDashboard/adminEdit.html
<html>
    <head>
        <title>Admin Edit </title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <style>
    {% load staticfiles %}
    .error {
      color:red;
      margin-left: 200px;
    }
    .green {
      color: green;
    }
    .btn {
      margin-top: 15px;
    }
    h1 {
      margin-left: 50px;
    }
    body {
    background-image: url('{% static "LoginAndReg/seigaiha.png" %}');
    }
    ul {
      list-style-type: none;
      display: inline-block;
      width: 70%;
    }
    li {
      display: inline-block;
      margin-left: 5%;
      margin-top: 1.5%;
      font-size: 1.5em;
    }
    a {
      color: rgb(55, 150, 239);
    }
    header li a {
      font-size: 1em;
    }
    header {
      background-color: rgb(1, 49, 94);
      color: white;
    }
    header a {
      font-size: 1.5em;
      margin-right: 2%;
    }
    .Manage {
      display: inline-block;
    }
</style>
    <body>
      <header>
        <ul>
          <li>TEST APP</li>
          <li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
          <li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Profile</a></li>
        </ul>
        {% if activeUser.user_level == "Admin" %}
        <a href="{%url 'UserDashboard:createDisplay' %}">Add New User</a>
        {% endif %}
        <a href="{%url 'UserDashboard:logout' %}">Log Off</a>
      </header>
      <form action="{%url 'login:updateInfo' id=User.id %}" method='post' class = "form-horizontal">
        {% csrf_token %}
          <h1> Edit {{User.firstName}}'s Information</h1>
          {% if error_messages.TwoCharacters %}
            <p class = 'error'> {{ error_messages.TwoCharacters }} </p>
          {% endif %}
          {% if error_messages.IsAlpha %}
            <p class = 'error'> {{ error_messages.IsAlpha }} </p>
          {% endif %}
          <div class = "form-group">
            <label for ="first_name" class="col-sm-2 control-label">First Name:</label>
            <div class = "col-sm-6">
              <input type='text' class = "form-control" name='first_name' id = "first_name" placeholder = "First Name"> 
            </div>
          </div>
          <div class = "form-group">
            <label for = "last_name" class = "col-sm-2 control-label">Last Name:</label>
            <div class = "col-sm-6">
              <input type='text' name='last_name' class = "form-control" id = "last_name" placeholder = "Last Name">
            </div>
          </div>
          {% if error_messages.EmailRequired %}
            <p class = 'error'> {{ error_messages.EmailRequired }} </p>
          {% endif %}
          {% if error_messages.InvalidEmail %}
            <p class = 'error'> {{ error_messages.InvalidEmail }} </p>
          {% endif %}
          {% if error_messages.EmailDuplicate %}
            <p class = 'error'> {{ error_messages.EmailDuplicate }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "email" class = "col-sm-2 control-label">Email:</label>
          <div class = "col-sm-6">
            <input type='text' name='email' class = "form-control" id = "email" placeholder = "Email">
          </div>
        </div>
        {% if error_messages.BirthdayError %}
            <p class = 'error'> {{ error_messages.BirthdayError }} </p>
        {% else %}
            {% if error_messages.BirthdayPast %}
              <p class = 'error'> {{ error_messages.BirthdayPast }} </p>
            {% endif %}
        {% endif %}
        <div class = "form-group">
          <label for = "birthday" class = "col-sm-2 control-label">Birthday:</label>
          <div class = "col-sm-6">
            <input type='date' name='birthday' class = "form-control" id = "birthday" placeholder = "Birthday">
            <input type='submit' value='Save' class = "btn btn-warning">
          </div>
        </div>
      </form>

     <form action="{%url 'login:updatePassword' id=User.id%}" method='post' class = "form-horizontal">
      {% csrf_token %}
         {% if error_messages.PasswordRequired %}
            <p class = 'error'> {{ error_messages.PasswordRequired }} </p>
          {% endif %}
          {% if error_messages.PasswordLength %}
            <p class = 'error'> {{ error_messages.PasswordLength }} </p>
          {% endif %}
          {% if error_messages.InvalidPassword %}
            <p class = 'error'> {{ error_messages.InvalidPassword }} </p>
          {% endif %}
          {% if error_messages.PasswordNonmatch %}
            <p class = 'error'> {{ error_messages.PasswordNonmatch }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "password" class = "col-sm-2 control-label">Password:</label>
          <div class = "col-sm-6">
            <input type='password' name='password' class = "form-control" id = "password" placeholder = "Password">
          </div>
        </div>
        <div class = "form-group">
          <label for = "confirmpassword" class = "col-sm-2 control-label">Confirm Password:</label>
          <div class = "col-sm-6">
            <input type='password' name='confirm_password' class = "form-control" id = "confirmpassword"placeholder = "Password">
            <input type='submit' value='Update Password' class = "btn btn-warning">
          </div>
        </div>
        </form>
    </body>
</html>

apps/UserDashboard/templates/UserDashboard/editProfile.html
<html>
    <head>
        <title>Login and Reg Index</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <style>
    {% load staticfiles %}
    .error {
      color:red;
      margin-left: 200px;
    }
    .green {
      color: green;
    }
    .btn {
      margin-top: 15px;
    }
    h1 {
      margin-left: 50px;
    }
    body {
    background-image: url('{% static "LoginAndReg/seigaiha.png" %}');
    }
    ul {
      list-style-type: none;
      display: inline-block;
      width: 70%;
    }
    li {
      display: inline-block;
      margin-left: 5%;
      margin-top: 1.5%;
      font-size: 1.5em;
    }
    a {
      color: rgb(55, 150, 239);
    }
    header li a {
      font-size: 1em;
    }
    header {
      background-color: rgb(1, 49, 94);
      color: white;
    }
    header a {
      font-size: 1.5em;
      margin-right: 2%;
    }
    .Manage {
      display: inline-block;
    }
</style>
    <body>
      <header>
        <ul>
          <li>TEST APP</li>
          <li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
          <li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Profile</a></li>
        </ul>
        {% if activeUser.user_level == "Admin" %}
        <a href="{%url 'UserDashboard:createDisplay' %}">Add New User</a>
        {% endif %}
        <a href="{%url 'UserDashboard:logout' %}">Log Off</a>
      </header>
      <form action="{%url 'login:updateInfo' id=0 %}" method='post' class = "form-horizontal">
        {% csrf_token %}
          <h1>Hello {{User.firstName}}, Edit Your Profile</h1>
          {% if TwoCharacters %}
            <p class = 'error'> {{ TwoCharacters }} </p>
          {% endif %}
          {% if IsAlpha %}
            <p class = 'error'> {{ IsAlpha }} </p>
          {% endif %}
          <div class = "form-group">
            <label for ="first_name" class="col-sm-2 control-label">First Name:</label>
            <div class = "col-sm-6">
              <input type='text' class = "form-control" name='first_name' id = "first_name" placeholder = "First Name"> 
            </div>
          </div>
          <div class = "form-group">
            <label for = "last_name" class = "col-sm-2 control-label">Last Name:</label>
            <div class = "col-sm-6">
              <input type='text' name='last_name' class = "form-control" id = "last_name" placeholder = "Last Name">
            </div>
          </div>
          {% if EmailRequired %}
            <p class = 'error'> {{ EmailRequired }} </p>
          {% endif %}
          {% if InvalidEmail %}
            <p class = 'error'> {{ InvalidEmail }} </p>
          {% endif %}
          {% if EmailDuplicate %}
            <p class = 'error'> {{ EmailDuplicate }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "email" class = "col-sm-2 control-label">Email:</label>
          <div class = "col-sm-6">
            <input type='text' name='email' class = "form-control" id = "email" placeholder = "Email">
          </div>
        </div>
        {% if BirthdayError %}
            <p class = 'error'> {{ BirthdayError }} </p>
        {% else %}
            {% if BirthdayPast %}
              <p class = 'error'> {{ BirthdayPast }} </p>
            {% endif %}
        {% endif %}
        <div class = "form-group">
          <label for = "birthday" class = "col-sm-2 control-label">Birthday:</label>
          <div class = "col-sm-6">
            <input type='date' name='birthday' class = "form-control" id = "birthday" placeholder = "Birthday">
            <input type='submit' value='Save' class = "btn btn-warning">
          </div>
        </div>
      </form>

     <form action="{%url 'login:updatePassword' id=0%}" method='post' class = "form-horizontal">
      {% csrf_token %}
         {% if PasswordRequired %}
            <p class = 'error'> {{ PasswordRequired }} </p>
          {% endif %}
          {% if PasswordLength %}
            <p class = 'error'> {{ PasswordLength }} </p>
          {% endif %}
          {% if InvalidPassword %}
            <p class = 'error'> {{ InvalidPassword }} </p>
          {% endif %}
          {% if PasswordNonmatch %}
            <p class = 'error'> {{ PasswordNonmatch }} </p>
          {% endif %}
        <div class = "form-group">
          <label for = "password" class = "col-sm-2 control-label">Password:</label>
          <div class = "col-sm-6">
            <input type='password' name='password' class = "form-control" id = "password" placeholder = "Password">
          </div>
        </div>
        <div class = "form-group">
          <label for = "confirmpassword" class = "col-sm-2 control-label">Confirm Password:</label>
          <div class = "col-sm-6">
            <input type='password' name='confirm_password' class = "form-control" id = "confirmpassword"placeholder = "Password">
            <input type='submit' value='Update Password' class = "btn btn-warning">
          </div>
        </div>
        </form>

       <form action="{%url 'login:updateDescription' %}" method='post' class = "form-horizontal">
        {% csrf_token %}
          <div class="form-group">
            <label for="description" class = "col-sm-2 control-label">Edit Description:</label>
            <div class = "col-sm-6">
            <textarea class="form-control" rows="5" name="description" id="description"></textarea>
            <input type='submit' value='Edit Description' class = "btn btn-warning">
           </div>
         </div>
       </form> 
    </body>
</html>

apps/UserDashboard/templates/UserDashboard/index.html
<html>
<head>
	<title>User_Dashboard</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<style>
	{% load staticfiles %}
	body {
		background-image: url('{% static "UserDashboard/congruent_pentagon.png" %}');
	}
	ul {
		list-style-type: none;
		display: inline-block;
		width: 70%;
	}
	li {
		display: inline-block;
		margin-left: 5%;
		margin-top: 1.5%;
		font-size: 1.5em;
		color: white;
	}
	a {
		color: rgb(55, 150, 239);
	}
	header li a {
		font-size: 1em;
	}
	header {
		background-color: rgb(1, 49, 94);
		color: white;
	}
	header a {
		font-size: 1.5em;
		margin-right: 2%;
	}
	.Manage {
		display: inline-block;
	}
</style>
<body>
	<header>
		<ul>
			<li>TEST APP</li>
			<li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
			<li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Profile</a></li>
		</ul>
		{% if activeUser.user_level == "Admin" %}
		<a href="{%url 'UserDashboard:createDisplay' %}">Add New User</a>
		{% endif %}
		<a href="{%url 'UserDashboard:logout' %}">Log Off</a>
	</header>
	<div class = "col-sm-4">
		<h2 class = "Manage">Manage Users</h2>
	</div>
	{% if activeUser.user_level == "Admin" %}
	<div class = "table-responsive col-sm-12">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Email</th>
				<th>Created At</th>
				<th>User Level</th>
				<th>Actions</th>
			</tr>	
		</thead>
		<tbody>
			{% for user in users %}
			<tr>
				<td>{{user.id}}</td>
				<td><a href="{%url 'UserDashboard:showWall' id=user.id %}">{{user.firstName}} {{user.lastName}}</a></td>
				<td>{{user.email}}</td>
				<td>{{user.created_at}}</td>
				<td>{{user.user_level}}</td>
				<td><a href="{%url 'UserDashboard:adminEdit' id=user.id %}">Edit</a> | <a href="{%url 'login:removeUser' id=user.id %}">Remove</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	</div>
	{% endif %}
	{% if activeUser.user_level == "Normal" %}
	<div class = "table-responsive col-sm-12">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Email</th>
				<th>Created At</th>
				<th>User Level</th>
			</tr>	
		</thead>
		<tbody>
			{% for user in users %}
			<tr>
				<td>{{user.id}}</td>
				<td><a href="{%url 'UserDashboard:showWall' id=user.id %}">{{user.firstName}} {{user.lastName}}</a></td>
				<td>{{user.email}}</td>
				<td>{{user.created_at}}</td>
				<td>{{user.user_level}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	<div>
	{% endif %}
</body>
</html>

apps/UserDashboard/templates/UserDashboard/showWall.html
<html>
<head>
	<title>The Wall</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
	<style>
	{% load staticfiles %}
	body {
		text-align: center;
		background-image: url('{% static "UserDashboard/skulls.png" %}');
	}
	.form-control {
		margin-bottom: 15px;
	}
	h2 {
		color: rgb(255, 123, 0);
		font-weight: 700;
		font-size: 40px;
	}
	p {
		color: rgb(12, 0, 147);
	}
	.container {
		text-align: left;
	}
	.logout {
		text-align: right;
		margin-right: 100px;
	}
	.message {
		font-size: 18px;
		font-weight: bold;
		margin: 0px;
		color: rgb(255, 42, 0);
	}
	.message1 {
		font-size: 16px;
		margin-top: 0px;
		margin-bottom: 10px;
		color: rgb(0, 7, 84);
	}
	.comment,
	.comment1 {
		margin-left: 50px;
		
	}
	.comment {
		font-weight: bold;
		font-size: 16px;
		margin-bottom: 0px;
		color: rgb(255, 42, 0);
	}
	.comment1 {
		font-size: 14px;
		margin-top: 0px;
		margin-bottom: 10px;
		color: rgb(0, 7, 84);
	}
	.comment-btn {
		margin-left: 50px;
	}
	.userlist {
		list-style-type: none;
		text-align: left;
		margin-left: 20%;
		font-size: 18px;
		color: black;
	}
	.headerul {
		list-style-type: none;
		display: inline-block;
		width: 80%;
	}
	.headerul li {
		display: inline-block;
		margin-left: 5%;
		margin-top: 1.5%;
		font-size: 1.5em;
	}
	.headerlink {
		color: rgb(18, 130, 234);
	}
	header li a {
		font-size: 1em;
		color: rgb(55, 150, 239)
	}
	header {
		background-color: rgb(1, 49, 94);
		text-align: left;
		color: white;
	}
	header a {
		font-size: 1.5em;
		margin-right: 2%;
	}
	.Manage {
		display: inline-block;
	}
	</style>
<body>
	<header>
		<ul class = "headerul">
			<li>TEST APP</li>
			<li><a href="{%url 'UserDashboard:index' %}">DashBoard</a></li>
			<li><a href="{%url 'UserDashboard:editProfileDisplay' %}">Profile</a></li>
		</ul>
		{% if activeUser.user_level == "Admin" %}
		<a class = "headerlink" href="{%url 'UserDashboard:createDisplay' %}">Add New User</a>
		{% endif %}
		<a class = "headerlink" href="{%url 'UserDashboard:logout' %}">Log Off</a>
	</header>
	<h2> {{user.firstName}}'s Wall</h2>
	<ul class = userlist>
		<li>Registered At: {{user.created_at}}</li>
		<li>User Id: #{{user.id}}</li>
		<li>Email Address: {{user.email}}</li>
		<li>Description: {{user.profileInformation}}</li>
	</ul>
	<div class = "container">
		<div class = "row">
			<div class = "col-sm-8 col-sm-offset-2">
				<form action="{% url 'UserDashboard:postMessage' %}" method='POST'>
					{% csrf_token %}
					<textarea class = "form-control" rows = "3" name = "message"></textarea>
				    <input type="submit" class = "btn btn-success" value="Message">
			  	</form>
	  		</div>
	  	</div>
 	</div>

 	<div class = "container">
 		<div class = "row">
 			<div class = "col-sm-8 col-sm-offset-2">
			  	{% for message in all_messages %}
			   <p class = "message">{{ message.user.firstName }} {{ message.user.lastName }} {{ message.created_at }}</p>
			   <p class = "message1">{{ message.message}}</p>
		   		{% if message.user.id == request.session.login %}
			   <form action = "{% url 'UserDashboard:deleteMessage' id=message.id %}" method = 'POST'>
			   	{% csrf_token %}
			   	 	<input type="submit" class = "btn btn-danger" value="Delete Message">
			   </form>
			   	{% endif %}
	   			{% for comment in all_comments %}
			   		{% if comment.message.id == message.id %}
		   			<p class= "comment"> {{ comment.user.firstName }} {{ comment.user.lastName }} {{ comment.created_at }} </p>
				   	<p class = "comment1"> {{ comment.comment }} </p>
				   	{% if comment.user_id == request.session.login %}
				   	<form action = "{% url 'UserDashboard:deleteComment' id=comment.id %}" method = 'POST'>
				   		{% csrf_token %}
				   	 	<input type="submit" value="Delete Comment" class = "btn btn-danger comment-btn">
				   	</form>
				   	{% endif %}
				   	{% endif %}
				   	{% endfor %}
				   	<form action="{% url 'UserDashboard:postComment' id=message.id %}" method='POST'>
				   		{% csrf_token %}
						<textarea rows = "3" class = "form-control" name = "comment"></textarea>
					    <input type="submit" value="Comment" class = "btn btn-warning">
			  		</form>
				{% endfor %}
			</div>
		</div>
	</div>
</body>
</html>